# Generated by Django 2.0.4 on 2018-04-11 05:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField()),
                ('start_date', models.DateField(null=True)),
                ('due_date', models.DateField(auto_now=True)),
                ('guarantor_declined', models.BooleanField(default=False)),
                ('admin_declined', models.BooleanField(default=False)),
                ('approved', models.BooleanField(default=False)),
                ('monthly_installment', models.PositiveIntegerField()),
                ('guaranted', models.BooleanField(default=False)),
                ('fulfilled', models.BooleanField(default=False)),
                ('guarantor', models.ForeignKey(on_delete='CASSCADE', related_name='guarantee', to=settings.AUTH_USER_MODEL)),
                ('owner', models.OneToOneField(on_delete='CASSCADE', related_name='loan', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary', models.PositiveIntegerField()),
                ('purse', models.PositiveIntegerField()),
                ('number', models.IntegerField()),
                ('role', models.BooleanField(default=False)),
                ('refrence_no', models.IntegerField()),
                ('picture', models.FileField(upload_to='media/user')),
                ('age', models.IntegerField()),
                ('user', models.OneToOneField(on_delete='CASSCADE', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
