# Generated by Django 2.0.4 on 2018-04-11 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooperative', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='purse',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
