# Generated by Django 2.0.4 on 2018-04-11 07:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooperative', '0003_auto_20180411_0727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='owner',
            field=models.ForeignKey(on_delete='CASSCADE', to=settings.AUTH_USER_MODEL),
        ),
    ]
