# Generated by Django 2.0.4 on 2018-04-11 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooperative', '0004_auto_20180411_0728'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='gurantor_name',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
