# Generated by Django 2.0.4 on 2018-04-11 08:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooperative', '0005_loan_gurantor_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='owner',
            field=models.ForeignKey(on_delete='CASSCADE', related_name='owner', to=settings.AUTH_USER_MODEL),
        ),
    ]
