# Generated by Django 2.0.4 on 2018-04-11 08:24

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cooperative', '0006_auto_20180411_0821'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Loan',
            new_name='Loandb',
        ),
    ]
