# Generated by Django 2.0.4 on 2018-04-11 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooperative', '0007_auto_20180411_0824'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanstatus',
            name='gurantor_status',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
