# Generated by Django 2.0.4 on 2018-04-12 01:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooperative', '0008_loanstatus_gurantor_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loandb',
            name='gurantor_name',
        ),
        migrations.RemoveField(
            model_name='loanstatus',
            name='guarantor_name',
        ),
        migrations.AddField(
            model_name='loandb',
            name='gurantor_email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='loandb',
            name='owner',
            field=models.ForeignKey(on_delete='CASSCADE', to=settings.AUTH_USER_MODEL),
        ),
    ]
