# Generated by Django 2.0.4 on 2018-04-12 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooperative', '0009_auto_20180412_0144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loandb',
            name='amount',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='loandb',
            name='monthly_installment',
            field=models.IntegerField(),
        ),
    ]
