# Generated by Django 2.0.4 on 2018-04-12 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cooperative', '0011_loandb_request'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loandb',
            old_name='owner',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='loanstatus',
            old_name='own',
            new_name='user',
        ),
    ]
