# Generated by Django 2.0.4 on 2018-04-12 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooperative', '0012_auto_20180412_0611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loandb',
            name='gurantor_email',
            field=models.EmailField(max_length=254),
        ),
    ]
