# Generated by Django 2.0.4 on 2018-04-12 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooperative', '0013_auto_20180412_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loandb',
            name='tenure',
            field=models.CharField(max_length=244),
        ),
    ]
