# Generated by Django 2.0.4 on 2018-04-14 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cooperative', '0014_auto_20180412_1215'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loandb',
            old_name='request',
            new_name='loan_request',
        ),
    ]
