# Generated by Django 2.0.4 on 2018-04-14 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooperative', '0015_auto_20180414_0800'),
    ]

    operations = [
        migrations.AddField(
            model_name='loandb',
            name='guarantee',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
