# Generated by Django 2.0.4 on 2018-04-14 16:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cooperative', '0016_loandb_guarantee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loanstatus',
            name='user',
        ),
        migrations.AddField(
            model_name='loanstatus',
            name='loan',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='cooperative.Loandb'),
        ),
        migrations.AlterField(
            model_name='loandb',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
