# Generated by Django 2.0.4 on 2018-04-16 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooperative', '0017_auto_20180414_1650'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loanstatus',
            name='loan',
        ),
        migrations.AddField(
            model_name='loandb',
            name='admin_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='loandb',
            name='gurantor_status',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.DeleteModel(
            name='LoanStatus',
        ),
    ]
