# Generated by Django 2.0.4 on 2018-04-17 05:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cooperative', '0018_auto_20180416_2328'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loanstatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_accept', models.CharField(max_length=300, null=True)),
                ('grant', models.CharField(max_length=300, null=True)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cooperative.Loandb')),
            ],
        ),
    ]
